import type { WhiteNoisePreset } from "./types";

export const WHITE_NOISE_PRESETS: WhiteNoisePreset[] = [
  {
    id: "rain",
    name: "Rainfall",
    emoji: "🌧️",
    volume: 0,
    isPremium: false,
    isActive: false,
  },
  {
    id: "thunder",
    name: "Thunderstorm",
    emoji: "⚡",
    volume: 0,
    isPremium: false,
    isActive: false,
  },
  {
    id: "fire",
    name: "Crackling Fire",
    emoji: "🔥",
    volume: 0,
    isPremium: false,
    isActive: false,
  },
  {
    id: "birds",
    name: "Forest Birds",
    emoji: "🐦",
    volume: 0,
    isPremium: false,
    isActive: false,
  },
  {
    id: "night",
    name: "Night Ambience",
    emoji: "🌙",
    volume: 0,
    isPremium: false,
    isActive: false,
  },
  {
    id: "ocean",
    name: "Ocean Waves",
    emoji: "🌊",
    volume: 0,
    isPremium: true,
    isActive: false,
  },
  {
    id: "cafe",
    name: "Café Ambience",
    emoji: "☕",
    volume: 0,
    isPremium: true,
    isActive: false,
  },
  {
    id: "keyboard",
    name: "Keyboard Typing",
    emoji: "⌨️",
    volume: 0,
    isPremium: true,
    isActive: false,
  },
  {
    id: "city",
    name: "City Ambience",
    emoji: "🏙️",
    volume: 0,
    isPremium: true,
    isActive: false,
  },
  {
    id: "white",
    name: "White Noise",
    emoji: "🤍",
    volume: 0,
    isPremium: false,
    isActive: false,
  },
  {
    id: "pink",
    name: "Pink Noise",
    emoji: "🩷",
    volume: 0,
    isPremium: false,
    isActive: false,
  },
  {
    id: "brown",
    name: "Brown Noise",
    emoji: "🤎",
    volume: 0,
    isPremium: false,
    isActive: false,
  },
];
