import {
  IconAlertTriangle,
  IconArrowRight,
  IconBrain,
  IconBrandDiscord,
  IconBrandFacebook,
  IconBrandGithub,
  IconBrandReddit,
  IconBrandTwitter,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconClock,
  IconCommand,
  IconCreditCard,
  IconDeviceLaptop,
  IconDotsVertical,
  IconFile,
  IconFileText,
  IconHelpCircle,
  IconLayoutDashboard,
  IconLayoutKanban,
  IconLoader2,
  IconLogin,
  IconMoon,
  IconPhoto,
  IconPizza,
  IconPlus,
  type IconProps,
  IconSettings,
  IconShoppingBag,
  IconSun,
  IconTrash,
  IconUser,
  IconUserCircle,
  IconUserEdit,
  IconUserX,
  IconX,
} from "@tabler/icons-react";

import {
  Book,
  BookOpen,
  Calendar,
  ChartLine,
  Folder,
  GraduationCap,
  LayoutPanelLeft,
  Library,
  MessageCircle,
  StickyNote,
  Timer,
  Trophy,
  Users,
  WandSparkles,
} from "lucide-react";

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
  dashboard: IconLayoutDashboard,
  logo: IconCommand,
  login: IconLogin,
  close: IconX,
  product: IconShoppingBag,
  spinner: IconLoader2,
  kanban: IconLayoutKanban,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  trash: IconTrash,
  employee: IconUserX,
  post: IconFileText,
  page: IconFile,
  userPen: IconUserEdit,
  user2: IconUserCircle,
  media: IconPhoto,
  settings: IconSettings,
  billing: IconCreditCard,
  ellipsis: IconDotsVertical,
  add: IconPlus,
  warning: IconAlertTriangle,
  user: IconUser,
  arrowRight: IconArrowRight,
  help: IconHelpCircle,
  brain: IconBrain,
  clock: IconClock,
  pizza: IconPizza,
  sun: IconSun,
  moon: IconMoon,
  laptop: IconDeviceLaptop,
  github: IconBrandGithub,
  twitter: IconBrandTwitter,
  check: IconCheck,
  // Brand Icons
  discord: IconBrandDiscord,
  facebook: IconBrandFacebook,
  reddit: IconBrandReddit,
  // Lucide Icons
  layoutPanelLeft: LayoutPanelLeft,
  library: Library,
  folder: Folder,
  book: Book,
  bookOpen: BookOpen,
  stickyNote: StickyNote,
  graduationCap: GraduationCap,
  timer: Timer,
  calendar: Calendar,
  users: Users,
  trophy: Trophy,
  chartLine: ChartLine,
  messageCircle: MessageCircle,
  wandSparkles: WandSparkles,
};
